FROM maven:3.8.4-jdk-11

WORKDIR /backend/edel-flies

# Copy Maven wrapper files
COPY .mvn/ .mvn
COPY mvnw pom.xml ./

# Make Maven wrapper executable and fetch dependencies
RUN chmod +x ./mvnw && ./mvnw dependency:go-offline

# Copy the source code
COPY src ./src

# Command to run your application (using Maven wrapper)
CMD ["./mvnw", "spring-boot:run"]